
name_list = [
    "Aegthorn",
    "Uilosra",
    "Saelrohir",
    "Shiphia",
    "Romar",
    "Riir",
    "Imorhel",
    "Rinlin",
    "Belegkraes",
    "Riaaeriel",
    "Imgorta",
    "Dwyrmorthas",
    "Onithir",
    "Rianva",
    "Ada",
    "Losrin",
    "Iemeril",
    "Imorev",
    "Linmor",
    "Dordal",
    "Rerath",
    "Tor",
    "Rytral",
    "Fleurco",
    "Kinli",
    "Phusclaw",
    "Rusau",
    "Shaco",
    "Larkma",
    "Diopvio",
    "Boltdon",
    "Raxgent",
    "Quercor",
    "Breathlai",
    "Gentktarrh",
    "Kordsos",
    "Chore",
    "Ta",
    "Dratin",
    "Hisswind",
    "Deonadben",
    "Dna'sau",
    "Gonriada",
    "Dyulrath",
    "Cogastul",
    "Lanvistha",
    "Nussamor",
    "Grimsape",
    "Nandnafiz",
    "Nanlaro",
    "Tsorontor",
    "Lonak",
    "Gau-wil",
    "Gus'gry",
    "Dallro",
    "Ma-man",
    "Mar-ki",
    "Gadermusnys",
    "Musspellspell",
    "Omgusa",    
    "Sythnorva",
    "Caiuhver",
    "Ssyshaash",
    "O'ur",
    "Gion'ltlish",
    "Gioncertys",
    "Ard'ban",
    "Rok-thslish",
    "Lobach'mar",
    "Freakoam",
    "Noryasuhn",
    "Drasmansis",
    "Kridrargjabhitl",
    "Le'ne",
    "Sith'man",
    "Simtharg",
    "Ta'hthis",
    "Zuskirsbael",
    "Ka-na",
    "Lai-'il",
]
weapon_name_list = [
    "Spartan's Valor",
    "Grim Reaper",
    "Blast Blazer",
    "Trigger Toppler",
    "Tempest",
    "Muzzle Meltdown",
    "Tsunami",
    "Godspeed",
    "Revenant's Wrath",
    "Phoenix ",
    "Ghostly Whisper",
    "Gunpowder Goliath",
    "Shadowblast",
    "Viper Strike",
    "Bullet Fury ",
    "Eclipse",
    "Havocmaker",
    "Samurai's Blade",
    "Blast Burner",
    "Cartridge Carnage "
]